feat: Add Pro components and Examples
featbit/featbit-charts pull request #2
Opened 2023-07-07 01:48 UTC by wss-rbrennan

Add Pro components and examples.

- reorganizes templates by resources type ex.  deployment-, service-, hpa-
- add environment variable templates for modules
- add helpers for pro, standard, and common names
- add example for standard without dependencies
- add example for standard version with dependencies
- add example for professional version without dependencies
- add example for professional version with all traditional dependencies (clickhouse, kafka, zookeeper, mongodb, redis)
- add example for professional version replacing zookeeper with kafka kraft mode, and clickhouse keeper.
- add the "charts" folder and dependency charts for easier first time deployment

2023-07-07 18:00 UTC, dsun0720 requested changes
Thank you very much for your contribution to the charts in the PRO section.

In your PR, you can add new YAML or TPL files without modifying the file names of existing files. This is because we already have a new branch in place based in v0.0.1 in order to optimize the auto discovery of externe IPs and backup mongoDB.

I hope you can understand.

2023-07-07 18:00 UTC, dsun0720 commented on .gitignore
> -charts/*/charts
I've created a GitHub action that will automatically package dependencies and publish this chart. No need to upload these dependence's packages

2023-07-07 19:02 UTC, wss-rbrennan commented on .gitignore
> -charts/*/charts
Yeah, I can change the file names back to their original names.  I'd like to recommend that post v0.0.2 that the names be grouped by resource type.

2023-07-07 19:15 UTC, wss-rbrennan commented on .gitignore
> -charts/*/charts
fixed with commit # d69a6e3

2023-07-08 07:27 UTC, dsun0720 requested changes
![截屏2023-07-08 09 22 12](https://github.com/featbit/featbit-charts/assets/38680131/bd351360-fbef-4901-b6eb-5eb05c4399e8)


can you add this limit in .github/release.yaml ? I'll publish a new release with your pr and v0.0.2. 

Thank you

2023-07-08 21:35 UTC, wss-rbrennan commented
> ![截屏2023-07-08 09 22 12](https://user-images.githubusercontent.com/38680131/251953140-bd351360-fbef-4901-b6eb-5eb05c4399e8.png)
> 
> can you add this limit in .github/release.yaml ? I'll publish a new release with your pr and v0.0.2.
> 
> Thank you

Added with commit # 17b8cae

2023-07-11 18:57 UTC, dsun0720 approved these changes

2023-07-11 18:57 UTC, merged